# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNITID', models.IntegerField()),
                ('INSTNM', models.CharField(max_length=50)),
                ('CITY', models.CharField(max_length=50)),
                ('STABBR', models.CharField(max_length=50)),
                ('Type', models.IntegerField()),
                ('DistFromChicago', models.IntegerField()),
                ('SimpleBarrons', models.CharField(max_length=50)),
                ('NetOrice0_30', models.IntegerField()),
                ('NetPrice30_48', models.IntegerField()),
                ('Percent_Male', models.DecimalField(decimal_places=20, max_digits=40)),
                ('Adj6yrGrad', models.DecimalField(decimal_places=20, max_digits=40)),
                ('Adj6yrGrad_AA_Hisp', models.DecimalField(decimal_places=20, max_digits=40)),
                ('RetentionAAH', models.DecimalField(decimal_places=20, max_digits=40)),
                ('AdjACT25', models.IntegerField()),
                ('Website', models.CharField(max_length=50)),
                ('Mean_Unmet_Need', models.DecimalField(decimal_places=20, max_digits=40)),
                ('Min_Unmet_Need', models.DecimalField(decimal_places=20, max_digits=40)),
                ('Max_Unmet_Need', models.DecimalField(decimal_places=20, max_digits=40)),
                ('Locale', models.CharField(max_length=50)),
                ('Number_Undergrads', models.IntegerField()),
                ('Pub_Private', models.CharField(max_length=50)),
                ('NobleAlumni', models.IntegerField()),
                ('NetPrice48_75', models.IntegerField()),
                ('Percent_Pell', models.DecimalField(decimal_places=20, max_digits=40)),
                ('MoneyFY13', models.CharField(max_length=50)),
                ('MoneyFY14', models.CharField(max_length=50)),
                ('AdjACT50', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACT', models.IntegerField()),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Index', models.CharField(max_length=50)),
                ('Strategy', models.IntegerField()),
                ('Fit', models.CharField(max_length=1)),
                ('Reach', models.CharField(max_length=1)),
                ('Safety', models.CharField(max_length=1)),
                ('Secure', models.CharField(max_length=1)),
                ('Race', models.CharField(max_length=1)),
            ],
        ),
    ]
