# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='Adj6yrGrad',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Adj6yrGrad_AA_Hisp',
        ),
        migrations.RemoveField(
            model_name='college',
            name='AdjACT25',
        ),
        migrations.RemoveField(
            model_name='college',
            name='AdjACT50',
        ),
        migrations.RemoveField(
            model_name='college',
            name='DistFromChicago',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Locale',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Max_Unmet_Need',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Mean_Unmet_Need',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Min_Unmet_Need',
        ),
        migrations.RemoveField(
            model_name='college',
            name='MoneyFY13',
        ),
        migrations.RemoveField(
            model_name='college',
            name='MoneyFY14',
        ),
        migrations.RemoveField(
            model_name='college',
            name='NetOrice0_30',
        ),
        migrations.RemoveField(
            model_name='college',
            name='NetPrice30_48',
        ),
        migrations.RemoveField(
            model_name='college',
            name='NetPrice48_75',
        ),
        migrations.RemoveField(
            model_name='college',
            name='NobleAlumni',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Number_Undergrads',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Percent_Male',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Percent_Pell',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Pub_Private',
        ),
        migrations.RemoveField(
            model_name='college',
            name='RetentionAAH',
        ),
        migrations.RemoveField(
            model_name='college',
            name='SimpleBarrons',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='college',
            name='Website',
        ),
        migrations.AddField(
            model_name='college',
            name='ADJ6YRGRAD',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='ADJ6YRGRAD_AA_HISP',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='ADJACT25',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='ADJACT50',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='DISTFROMCHICAGO',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='LOCALE',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='MAX_UNMET_NEED',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='MEAN_UNMET_NEED',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='MIN_UNMET_NEED',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='MONEYFY13',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='MONEYFY14',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='NETPRICE0_30',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='NETPRICE30_48',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='NETPRICE48_75',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='NOBLEALUMNI',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='NUMBER_UNDERGRADS',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='PERCENT_MALE',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='PERCENT_PELL',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='PUB_PRIVATE',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='RETENTIONAAH',
            field=models.DecimalField(decimal_places=20, default='0000000', max_digits=40),
        ),
        migrations.AddField(
            model_name='college',
            name='SIMPLEBARRONS',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='TYPE',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='college',
            name='WEBSITE',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='CITY',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='INSTNM',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='STABBR',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='UNITID',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ACT',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fit',
            field=models.CharField(default='Test', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, default='0000000', max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='Index',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=models.CharField(default='Test', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Reach',
            field=models.CharField(default='Test', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Safety',
            field=models.CharField(default='Test', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Secure',
            field=models.CharField(default='Test', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Strategy',
            field=models.IntegerField(default='0'),
        ),
    ]
