# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0002_auto_20160714_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='TYPE',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
