# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0003_auto_20160714_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='MONEYFY14_CATEGORY',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
