# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0004_college_moneyfy14_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='NETPRICE0_30',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='NETPRICE30_48',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='NETPRICE48_75',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
