# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0006_auto_20160714_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='ADJ6YRGRAD',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='ADJ6YRGRAD_AA_HISP',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='ADJACT25',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
