# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0009_auto_20160714_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='MAX_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='MEAN_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='MIN_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='PERCENT_PELL',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
