# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialbot', '0013_auto_20160714_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='ADJ6YRGRAD',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ADJ6YRGRAD_AA_HISP',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ADJACT25',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ADJACT50',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='CITY',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='DISTFROMCHICAGO',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='INSTNM',
            field=models.CharField(default='Test', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='LOCALE',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MAX_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MEAN_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MIN_UNMET_NEED',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MONEYFY13',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MONEYFY14',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='MONEYFY14_CATEGORY',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='NETPRICE0_30',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='NETPRICE30_48',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='NETPRICE48_75',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='NOBLEALUMNI',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='NUMBER_UNDERGRADS',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='PERCENT_MALE',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='PERCENT_PELL',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='PUB_PRIVATE',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='RETENTIONAAH',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='SIMPLEBARRONS',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='STABBR',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='TYPE',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='WEBSITE',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fit',
            field=models.CharField(default='Test', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Index',
            field=models.CharField(default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=models.CharField(default='Test', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Reach',
            field=models.CharField(default='Test', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Safety',
            field=models.CharField(default='Test', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Secure',
            field=models.CharField(default='Test', max_length=1, null=True),
        ),
    ]
